# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f92ce0281098cb655fe8524467797469d6a89fca2aa7a8256c8f72c4789c0cddbf16ff7f5ec88d3cbed6b4b48769bbe756f58627f0f78b6bd185b40e74fdb53

test:
  secret_key_base: adf5b3c1b948cad2a99314d351c3a12cc3442792124fac60c092faaf1cb906b04c29aa78acd7f8a9051263d9d336315576301fcd5e4c979bbf91f9ce07a71897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
